# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review.ui'
#
# Created: Tue Jul 29 00:46:47 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 900)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_64 = QtGui.QLabel(self.groupBox)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout_5.addWidget(self.label_64)
        self.line_6 = QtGui.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_5.addWidget(self.line_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_128 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_128.setFont(font)
        self.label_128.setObjectName(_fromUtf8("label_128"))
        self.horizontalLayout_3.addWidget(self.label_128)
        self.label_129 = QtGui.QLabel(self.groupBox)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.horizontalLayout_3.addWidget(self.label_129)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_130 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_130.setFont(font)
        self.label_130.setObjectName(_fromUtf8("label_130"))
        self.horizontalLayout_3.addWidget(self.label_130)
        self.label_131 = QtGui.QLabel(self.groupBox)
        self.label_131.setObjectName(_fromUtf8("label_131"))
        self.horizontalLayout_3.addWidget(self.label_131)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_132 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_132.setFont(font)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.horizontalLayout_4.addWidget(self.label_132)
        self.label_133 = QtGui.QLabel(self.groupBox)
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.horizontalLayout_4.addWidget(self.label_133)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_75 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_4.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.groupBox)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_4.addWidget(self.label_76)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_9 = QtGui.QFrame(self.groupBox)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_2.addWidget(self.line_9)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 1, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 1, 7, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 6, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 0, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 0, 6, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 0, 7, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 0, 4, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 1, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 1, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 1, 6, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_3.addWidget(self.label_38, 1, 7, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 5, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_39 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 3, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_4.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_4.addWidget(self.label_45, 0, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_4.addWidget(self.label_46, 2, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_4.addWidget(self.label_47, 2, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_4.addWidget(self.label_48, 3, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_4.addWidget(self.label_49, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_4 = QtGui.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_50 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_5.addWidget(self.label_53, 2, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_5.addWidget(self.label_54, 3, 0, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_5.addWidget(self.label_55, 1, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_5.addWidget(self.label_56, 0, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_5.addWidget(self.label_57, 2, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBox)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_5.addWidget(self.label_58, 2, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBox)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_5.addWidget(self.label_59, 3, 1, 1, 1)
        self.label_60 = QtGui.QLabel(self.groupBox)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_5.addWidget(self.label_60, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.line_5 = QtGui.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_2.addWidget(self.line_5)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_62 = QtGui.QLabel(self.groupBox)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_6.addWidget(self.label_62, 1, 4, 1, 1)
        self.label_63 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_6.addWidget(self.label_63, 0, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBox)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_6.addWidget(self.label_65, 0, 4, 1, 1)
        self.label_61 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_6.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_6.addWidget(self.label_68, 1, 3, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_6.addWidget(self.label_71, 0, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 5, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_6.addWidget(self.label_70, 1, 1, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_6.addWidget(self.label_69, 1, 0, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_6.addWidget(self.label_67, 0, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_6.addWidget(self.label_66, 0, 7, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem10)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_89 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_8.addWidget(self.label_89, 0, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_5, 0, 8, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_3.setDecimals(4)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_3, 0, 4, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setDecimals(4)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_4, 0, 6, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setDecimals(4)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_2, 0, 2, 1, 1)
        self.label_88 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_8.addWidget(self.label_88, 0, 7, 1, 1)
        self.label_95 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_8.addWidget(self.label_95, 0, 5, 1, 1)
        self.label_92 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_92.setFont(font)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_8.addWidget(self.label_92, 0, 3, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_8.addWidget(self.label_72, 1, 3, 1, 1)
        self.label_91 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_8.addWidget(self.label_91, 1, 7, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_8)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem11)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem12)
        self.tableView = QtGui.QTableView(self.groupBox_4)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_8.addWidget(self.tableView)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_10.addItem(spacerItem13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton = QtGui.QPushButton(self.groupBox_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/revise.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.label_73 = QtGui.QLabel(self.groupBox_2)
        self.label_73.setText(_fromUtf8(""))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_10.addWidget(self.label_73)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_10.addItem(spacerItem14)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.graphicsView_6 = QtGui.QGraphicsView(self.tab_7)
        self.graphicsView_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_6.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.verticalLayout_9.addWidget(self.graphicsView_6)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.tab_2)
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_2.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_3.addWidget(self.graphicsView_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.tab_3)
        self.graphicsView_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_3.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_3.setTransformationAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView_3.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.verticalLayout_4.addWidget(self.graphicsView_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.graphicsView_4 = QtGui.QGraphicsView(self.tab_4)
        self.graphicsView_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_4.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_4.setObjectName(_fromUtf8("graphicsView_4"))
        self.verticalLayout_5.addWidget(self.graphicsView_4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.graphicsView_5 = QtGui.QGraphicsView(self.tab_5)
        self.graphicsView_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_5.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.verticalLayout_6.addWidget(self.graphicsView_5)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_8)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.verticalLayout_11.addWidget(self.textBrowser_2)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_6)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_12.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "review", None))
        self.label_64.setText(_translate("MainWindow", "Focal Mechanism", None))
        self.label_128.setText(_translate("MainWindow", "Event ID", None))
        self.label_129.setText(_translate("MainWindow", "None", None))
        self.label_130.setText(_translate("MainWindow", "Origin ID", None))
        self.label_131.setText(_translate("MainWindow", "None", None))
        self.label_132.setText(_translate("MainWindow", "Origin Timestamp", None))
        self.label_133.setText(_translate("MainWindow", "None", None))
        self.label_75.setText(_translate("MainWindow", "Type", None))
        self.label_76.setText(_translate("MainWindow", "None", None))
        self.label_16.setText(_translate("MainWindow", "None", None))
        self.label_10.setText(_translate("MainWindow", "None", None))
        self.label_9.setText(_translate("MainWindow", "Origin Time (GMT)", None))
        self.label_14.setText(_translate("MainWindow", "None", None))
        self.label_15.setText(_translate("MainWindow", "Moment (Nm)", None))
        self.label.setText(_translate("MainWindow", "Origin Date (GMT)", None))
        self.label_11.setText(_translate("MainWindow", "Centroid Longitude", None))
        self.label_12.setText(_translate("MainWindow", "Centroid Time (sec)", None))
        self.label_3.setText(_translate("MainWindow", "Centroid Latitude", None))
        self.label_5.setText(_translate("MainWindow", "Centroid Depth (km)", None))
        self.label_13.setText(_translate("MainWindow", "None", None))
        self.label_2.setText(_translate("MainWindow", "None", None))
        self.label_4.setText(_translate("MainWindow", "None", None))
        self.label_7.setText(_translate("MainWindow", "Mw", None))
        self.label_8.setText(_translate("MainWindow", "None", None))
        self.label_6.setText(_translate("MainWindow", "None", None))
        self.label_21.setText(_translate("MainWindow", "DC (%)", None))
        self.label_17.setText(_translate("MainWindow", "Correlation", None))
        self.label_24.setText(_translate("MainWindow", "None", None))
        self.label_22.setText(_translate("MainWindow", "Variance Reduction", None))
        self.label_26.setText(_translate("MainWindow", "None", None))
        self.label_23.setText(_translate("MainWindow", "None", None))
        self.label_25.setText(_translate("MainWindow", "CLVD (%)", None))
        self.label_18.setText(_translate("MainWindow", "None", None))
        self.label_19.setText(_translate("MainWindow", "VOL (%)", None))
        self.label_20.setText(_translate("MainWindow", "None", None))
        self.label_27.setText(_translate("MainWindow", "Mrr", None))
        self.label_28.setText(_translate("MainWindow", "None", None))
        self.label_29.setText(_translate("MainWindow", "Mtt", None))
        self.label_31.setText(_translate("MainWindow", "Mpp", None))
        self.label_32.setText(_translate("MainWindow", "None", None))
        self.label_30.setText(_translate("MainWindow", "None", None))
        self.label_33.setText(_translate("MainWindow", "Mrt", None))
        self.label_35.setText(_translate("MainWindow", "Mrp", None))
        self.label_36.setText(_translate("MainWindow", "None", None))
        self.label_37.setText(_translate("MainWindow", "Mtp", None))
        self.label_38.setText(_translate("MainWindow", "None", None))
        self.label_34.setText(_translate("MainWindow", "None", None))
        self.label_39.setText(_translate("MainWindow", "Strike", None))
        self.label_42.setText(_translate("MainWindow", "None", None))
        self.label_43.setText(_translate("MainWindow", "NP1", None))
        self.label_40.setText(_translate("MainWindow", "Dip", None))
        self.label_41.setText(_translate("MainWindow", "Rake", None))
        self.label_44.setText(_translate("MainWindow", "None", None))
        self.label_45.setText(_translate("MainWindow", "NP2", None))
        self.label_46.setText(_translate("MainWindow", "None", None))
        self.label_47.setText(_translate("MainWindow", "None", None))
        self.label_48.setText(_translate("MainWindow", "None", None))
        self.label_49.setText(_translate("MainWindow", "None", None))
        self.label_50.setText(_translate("MainWindow", "P-axis", None))
        self.label_51.setText(_translate("MainWindow", "None", None))
        self.label_52.setText(_translate("MainWindow", "Azimuth", None))
        self.label_53.setText(_translate("MainWindow", "T-axis", None))
        self.label_54.setText(_translate("MainWindow", "B-axis", None))
        self.label_55.setText(_translate("MainWindow", "None", None))
        self.label_56.setText(_translate("MainWindow", "Plunge", None))
        self.label_57.setText(_translate("MainWindow", "None", None))
        self.label_58.setText(_translate("MainWindow", "None", None))
        self.label_59.setText(_translate("MainWindow", "None", None))
        self.label_60.setText(_translate("MainWindow", "None", None))
        self.label_62.setText(_translate("MainWindow", "None", None))
        self.label_63.setText(_translate("MainWindow", "Max Singular Value", None))
        self.label_65.setText(_translate("MainWindow", "None", None))
        self.label_61.setText(_translate("MainWindow", "Min Singular Value", None))
        self.label_68.setText(_translate("MainWindow", "FMVAR", None))
        self.label_71.setText(_translate("MainWindow", "Condition Number", None))
        self.label_70.setText(_translate("MainWindow", "None", None))
        self.label_69.setText(_translate("MainWindow", "STVAR", None))
        self.label_67.setText(_translate("MainWindow", "None", None))
        self.label_66.setText(_translate("MainWindow", "None", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Revision", None))
        self.label_89.setText(_translate("MainWindow", "Freq Band (Hz)", None))
        self.label_88.setText(_translate("MainWindow", "-", None))
        self.label_95.setText(_translate("MainWindow", "and", None))
        self.label_92.setText(_translate("MainWindow", "-", None))
        self.label_72.setText(_translate("MainWindow", "tapered", None))
        self.label_91.setText(_translate("MainWindow", "tapered", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Stream Contribution (variance reduction per component)", None))
        self.checkBox.setText(_translate("MainWindow", "all", None))
        self.pushButton_2.setText(_translate("MainWindow", "delete", None))
        self.pushButton.setText(_translate("MainWindow", "revise", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "misfit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "inversion", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "correlation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "streams", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "log", None))

import icons_rc
