# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Tue Jul 29 00:46:47 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo/beachball.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_14.setInputMask(_fromUtf8(""))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_9.addWidget(self.lineEdit_14, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 1, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_5.setMaximum(99999999)
        self.spinBox_5.setProperty("value", 1000)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_9.addWidget(self.spinBox_5, 2, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 2, 2, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_9.addWidget(self.lineEdit_15, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 3, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setProperty("value", 3.5)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_12.addWidget(self.doubleSpinBox_4, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_10)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem5, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_10.addWidget(self.label_25, 3, 1, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_12)
        self.spinBox_6.setMaximum(99999999)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_10.addWidget(self.spinBox_6, 2, 5, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 2, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_10.addWidget(self.doubleSpinBox_2, 3, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem9, 4, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_12)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 1, 5, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_12)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 2, 1, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_12)
        self.spinBox_8.setMaximum(99999999)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_10.addWidget(self.spinBox_8, 3, 5, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_12)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_10.addWidget(self.label_28, 1, 2, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_10.addWidget(self.doubleSpinBox, 2, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem10, 3, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_12)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_10.addWidget(self.label_49, 3, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem11, 3, 6, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_12)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_10.addWidget(self.label_31, 2, 4, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 2, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_10)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolButton = QtGui.QToolButton(self.groupBox_12)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.verticalLayout_3.addWidget(self.toolButton)
        self.toolButton_2 = QtGui.QToolButton(self.groupBox_12)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_3.addWidget(self.toolButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.listWidget = QtGui.QListWidget(self.groupBox_12)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_12)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.comboBox = QtGui.QComboBox(self.groupBox_11)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_11)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_13.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_11)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_13.addWidget(self.label_27, 1, 0, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_11)
        self.spinBox_7.setProperty("value", 2)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_13.addWidget(self.spinBox_7, 2, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem15, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem17 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.pushButton_17 = QtGui.QPushButton(self.groupBox_13)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon3)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_6.addWidget(self.pushButton_17)
        spacerItem18 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem19)
        self.label_5 = QtGui.QLabel(self.groupBox_13)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.horizontalLayout_5.addWidget(self.groupBox_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem20)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_29 = QtGui.QLabel(self.groupBox_16)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_11.addWidget(self.label_29)
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox_16)
        self.spinBox_13.setProperty("value", 15)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.horizontalLayout_11.addWidget(self.spinBox_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_30 = QtGui.QLabel(self.groupBox_16)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_12.addWidget(self.label_30)
        self.spinBox_14 = QtGui.QSpinBox(self.groupBox_16)
        self.spinBox_14.setMaximum(999)
        self.spinBox_14.setProperty("value", 2)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.horizontalLayout_12.addWidget(self.spinBox_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addWidget(self.groupBox_16)
        self.groupBox_18 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem21)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_41 = QtGui.QLabel(self.groupBox_18)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_14.addWidget(self.label_41)
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_18)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_14.addWidget(self.lineEdit_19)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_18)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/browse.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon4)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_14.addWidget(self.pushButton_14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_15.addWidget(self.groupBox_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem22)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_40 = QtGui.QLabel(self.groupBox_19)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_9.addWidget(self.label_40)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_8.setMaximum(1.0)
        self.doubleSpinBox_8.setProperty("value", 0.8)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.verticalLayout_14.addWidget(self.groupBox_19)
        self.groupBox_17 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtGui.QFormLayout.FieldRole, spacerItem23)
        self.label_46 = QtGui.QLabel(self.groupBox_17)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_47 = QtGui.QLabel(self.groupBox_17)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_47)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_17)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_48 = QtGui.QLabel(self.groupBox_17)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_48)
        self.spinBox_15 = QtGui.QSpinBox(self.groupBox_17)
        self.spinBox_15.setMaximum(999)
        self.spinBox_15.setProperty("value", 2)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_15)
        self.verticalLayout_11.addLayout(self.formLayout)
        self.verticalLayout_14.addWidget(self.groupBox_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_33 = QtGui.QLabel(self.groupBox_14)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_11.addWidget(self.label_33, 1, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_14)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 1, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem24, 0, 2, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem25, 2, 3, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_11.addWidget(self.doubleSpinBox_3, 2, 2, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem26, 2, 5, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_5.setDecimals(1)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_11.addWidget(self.doubleSpinBox_5, 3, 2, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem27, 4, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_14)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_11.addWidget(self.label_34, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_14)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_11.addWidget(self.label_32, 3, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_14)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_2, 2, 4, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_11)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolButton_3 = QtGui.QToolButton(self.groupBox_14)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.verticalLayout_5.addWidget(self.toolButton_3)
        self.toolButton_4 = QtGui.QToolButton(self.groupBox_14)
        self.toolButton_4.setIcon(icon2)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.verticalLayout_5.addWidget(self.toolButton_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_14)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.horizontalLayout_7.addWidget(self.listWidget_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_14)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_42 = QtGui.QLabel(self.groupBox_15)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_19.addWidget(self.label_42, 1, 4, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_15)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_19.addWidget(self.label_54, 1, 2, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem29, 0, 2, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem30, 2, 3, 1, 1)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_9.setDecimals(1)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_9, 2, 2, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem31, 2, 5, 1, 1)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_12.setDecimals(1)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_12, 3, 2, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem32, 4, 2, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_15)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_19.addWidget(self.label_55, 2, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_15)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_19.addWidget(self.label_56, 3, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_13.setDecimals(4)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_13)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_14.setDecimals(4)
        self.doubleSpinBox_14.setObjectName(_fromUtf8("doubleSpinBox_14"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_14)
        self.doubleSpinBox_18 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_18.setDecimals(4)
        self.doubleSpinBox_18.setObjectName(_fromUtf8("doubleSpinBox_18"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_18)
        self.doubleSpinBox_19 = QtGui.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_19.setDecimals(4)
        self.doubleSpinBox_19.setObjectName(_fromUtf8("doubleSpinBox_19"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_19)
        self.gridLayout_19.addLayout(self.horizontalLayout_13, 2, 4, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_19)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem33)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.toolButton_5 = QtGui.QToolButton(self.groupBox_15)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.verticalLayout_7.addWidget(self.toolButton_5)
        self.toolButton_6 = QtGui.QToolButton(self.groupBox_15)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.verticalLayout_7.addWidget(self.toolButton_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.listWidget_3 = QtGui.QListWidget(self.groupBox_15)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.horizontalLayout_8.addWidget(self.listWidget_3)
        self.verticalLayout_2.addWidget(self.groupBox_15)
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_23.addItem(spacerItem34)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_18.addWidget(self.label_16)
        self.spinBox_2 = QtGui.QSpinBox(self.tab_4)
        self.spinBox_2.setMaximum(99999)
        self.spinBox_2.setProperty("value", 60)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_18.addWidget(self.spinBox_2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_19.addWidget(self.label_17)
        self.spinBox_3 = QtGui.QSpinBox(self.tab_4)
        self.spinBox_3.setMaximum(99999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_19.addWidget(self.spinBox_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        self.spinBox_4 = QtGui.QSpinBox(self.tab_4)
        self.spinBox_4.setMaximum(99999)
        self.spinBox_4.setProperty("value", 3600)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_20.addWidget(self.spinBox_4)
        self.verticalLayout_23.addLayout(self.horizontalLayout_20)
        spacerItem35 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem35)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_2 = QtGui.QLabel(self.groupBox_8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_17.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_17.addWidget(self.pushButton_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_19.addItem(spacerItem36)
        self.groupBox_20 = QtGui.QGroupBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem37)
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon5)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_15.addWidget(self.pushButton_13)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem38)
        self.checkBox = QtGui.QCheckBox(self.groupBox_20)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_15.addWidget(self.checkBox)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem39)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_19.addWidget(self.groupBox_20)
        self.gridLayout_7.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout_7.addItem(spacerItem40, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem41 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem41)
        self.groupBox_21 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_21)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_43 = QtGui.QLabel(self.groupBox_21)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_16.addWidget(self.label_43, 3, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_16.addWidget(self.lineEdit_20, 3, 1, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_21)
        self.pushButton_16.setIcon(icon4)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_16.addWidget(self.pushButton_16, 3, 2, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_16.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_21)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_16.addWidget(self.label_44, 2, 0, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.groupBox_21)
        self.pushButton_18.setIcon(icon4)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_16.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setTitle(_fromUtf8(""))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_22)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_17.addWidget(self.lineEdit_22, 0, 1, 1, 5)
        self.label_45 = QtGui.QLabel(self.groupBox_22)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_17.addWidget(self.label_45, 1, 0, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox_22)
        self.spinBox_9.setMaximum(99999)
        self.spinBox_9.setProperty("value", 18000)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_17.addWidget(self.spinBox_9, 1, 6, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.groupBox_22)
        self.pushButton_19.setIcon(icon4)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_17.addWidget(self.pushButton_19, 0, 6, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_22)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_17.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_22)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_17.addWidget(self.label_51, 1, 4, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_17.addWidget(self.lineEdit_23, 1, 1, 1, 2)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem42, 1, 3, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_22, 4, 1, 1, 2)
        self.label_52 = QtGui.QLabel(self.groupBox_21)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_16.addWidget(self.label_52, 4, 0, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_16.addWidget(self.lineEdit_24, 1, 1, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.groupBox_21)
        self.pushButton_20.setIcon(icon4)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_16.addWidget(self.pushButton_20, 1, 2, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_21)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_16.addWidget(self.label_53, 1, 0, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem43, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_21)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem44)
        self.groupBox_9 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 2px; \n"
" }"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_3 = QtGui.QLabel(self.groupBox_9)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_21.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_21.addWidget(self.lineEdit_3)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_21.addWidget(self.pushButton_9)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        self.gridLayout_15.addLayout(self.verticalLayout_21, 1, 0, 1, 1)
        spacerItem45 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem45, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem46 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem46)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem47 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem47)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem48)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem49)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem50 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem50)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Location\'s restriction", None))
        self.lineEdit_14.setText(_translate("MainWindow", "0.0000", None))
        self.label_20.setText(_translate("MainWindow", "center latitude", None))
        self.label_19.setText(_translate("MainWindow", "center longitude", None))
        self.label_23.setText(_translate("MainWindow", "distance range (km)", None))
        self.lineEdit_15.setText(_translate("MainWindow", "0.0000", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Magnitude\'s restriction", None))
        self.label_26.setText(_translate("MainWindow", "min magnitude", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Distance selection", None))
        self.label_25.setText(_translate("MainWindow", "max", None))
        self.label_22.setText(_translate("MainWindow", "distance (km)", None))
        self.label_24.setText(_translate("MainWindow", "min", None))
        self.label_28.setText(_translate("MainWindow", "magnitude", None))
        self.label_49.setText(_translate("MainWindow", "max", None))
        self.label_31.setText(_translate("MainWindow", "min", None))
        self.toolButton.setText(_translate("MainWindow", "add", None))
        self.toolButton_2.setText(_translate("MainWindow", "remove", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "3.5 <= magnitude <= 12.0 and 0 <= distance <= 1000", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_11.setTitle(_translate("MainWindow", "Azimuthal selection", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "3", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "4", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "5", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "6", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "7", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "8", None))
        self.label_21.setText(_translate("MainWindow", "stations per sector", None))
        self.label_27.setText(_translate("MainWindow", "number of sectors", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Stations", None))
        self.pushButton_17.setText(_translate("MainWindow", "edit database", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "stations", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Centroid depth", None))
        self.label_29.setText(_translate("MainWindow", "number of sources", None))
        self.label_30.setText(_translate("MainWindow", "step search (km)", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "Crustal model", None))
        self.label_41.setText(_translate("MainWindow", "crustal model path", None))
        self.lineEdit_19.setText(_translate("MainWindow", "./crustal_model", None))
        self.pushButton_14.setText(_translate("MainWindow", "browse", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Data clipping", None))
        self.label_40.setText(_translate("MainWindow", "clipping threshold", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "Time grid search", None))
        self.label_46.setText(_translate("MainWindow", "start", None))
        self.lineEdit_17.setText(_translate("MainWindow", "-75", None))
        self.label_47.setText(_translate("MainWindow", "end", None))
        self.lineEdit_18.setText(_translate("MainWindow", "75", None))
        self.label_48.setText(_translate("MainWindow", "step search", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Inversion time", None))
        self.label_33.setText(_translate("MainWindow", "tl (sec)", None))
        self.label_35.setText(_translate("MainWindow", "magnitude", None))
        self.label_34.setText(_translate("MainWindow", "min", None))
        self.label_32.setText(_translate("MainWindow", "max", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "16.384", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "40.96", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "81.92", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "163.84", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "245.76", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "327.68", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "409.6", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "819.2", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "1638.4", None))
        self.toolButton_3.setText(_translate("MainWindow", "add", None))
        self.toolButton_4.setText(_translate("MainWindow", "remove", None))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "3.5 <= magnitude <= 12.0 and tl = 327.680", None))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.groupBox_15.setTitle(_translate("MainWindow", "Inversion frequency", None))
        self.label_42.setText(_translate("MainWindow", "frequencies (Hz)", None))
        self.label_54.setText(_translate("MainWindow", "magnitude", None))
        self.label_55.setText(_translate("MainWindow", "min", None))
        self.label_56.setText(_translate("MainWindow", "max", None))
        self.toolButton_5.setText(_translate("MainWindow", "add", None))
        self.toolButton_6.setText(_translate("MainWindow", "remove", None))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "3.5 <= magnitude <= 12.0 and frequencies = [0.04, 0.05, 0.08, 0.09]", None))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "inversion", None))
        self.label_16.setText(_translate("MainWindow", "check interval (sec)", None))
        self.label_17.setText(_translate("MainWindow", "process triggering delay (sec)", None))
        self.label_18.setText(_translate("MainWindow", "process timeout (sec)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "watcher", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "scisola", None))
        self.label_2.setText(_translate("MainWindow", "results folder", None))
        self.lineEdit_2.setText(_translate("MainWindow", "./results", None))
        self.pushButton_2.setText(_translate("MainWindow", "browse", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "scisola database", None))
        self.pushButton_13.setText(_translate("MainWindow", "update database", None))
        self.checkBox.setText(_translate("MainWindow", "reset", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "SeisComP3", None))
        self.label_43.setText(_translate("MainWindow", "scxmldump path", None))
        self.lineEdit_20.setText(_translate("MainWindow", "scxmldump", None))
        self.pushButton_16.setText(_translate("MainWindow", "browse", None))
        self.lineEdit_21.setText(_translate("MainWindow", "scevtls", None))
        self.label_44.setText(_translate("MainWindow", "scevtls path", None))
        self.pushButton_18.setText(_translate("MainWindow", "browse", None))
        self.lineEdit_22.setText(_translate("MainWindow", "slinktool", None))
        self.label_45.setText(_translate("MainWindow", "host", None))
        self.pushButton_19.setText(_translate("MainWindow", "browse", None))
        self.label_50.setText(_translate("MainWindow", "path", None))
        self.label_51.setText(_translate("MainWindow", "port", None))
        self.lineEdit_23.setText(_translate("MainWindow", "localhost", None))
        self.label_52.setText(_translate("MainWindow", "slinktool", None))
        self.lineEdit_24.setText(_translate("MainWindow", "/home/sysop/seiscomp3/bin/seiscomp", None))
        self.pushButton_20.setText(_translate("MainWindow", "browse", None))
        self.label_53.setText(_translate("MainWindow", "SeisComP3 path", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "ISOLA", None))
        self.label_3.setText(_translate("MainWindow", "ISOLA path", None))
        self.lineEdit_3.setText(_translate("MainWindow", "../ISOLA", None))
        self.pushButton_9.setText(_translate("MainWindow", "browse", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "settings", None))
        self.label.setText(_translate("MainWindow", "Last changes:", None))
        self.label_4.setText(_translate("MainWindow", "-", None))
        self.pushButton.setText(_translate("MainWindow", "apply", None))

import icons_rc
